import assert from "node:assert/strict";
import { getChatbotReply } from "./reply.ts";

const conversations = [
  {
    name: "budget language",
    messages: [
      "I have 4k, what can I eat?",
      "What can I get for four thousand?",
      "I'm broke 😂 what can I eat?",
      "What food is within my budget?",
      "I only have 3000 naira.",
    ],
    expected: [
      "Amala & Gbegiri at ₦3,000.",
      "Amala & Gbegiri at ₦3,000.",
      "Amala & Gbegiri at ₦3,000.",
      "Amala & Gbegiri at ₦3,000.",
      "Amala & Gbegiri at ₦3,000.",
    ],
  },
  {
    name: "delivery language",
    messages: [
      "Do you guys deliver?",
      "Can you bring food to me?",
      "Do you deliver in Lagos?",
      "Can I get delivery?",
      "I want my food delivered.",
    ],
    expected: [
      "Yes, within Lagos State.",
      "Yes, within Lagos State.",
      "Yes, within Lagos State.",
      "Yes, within Lagos State.",
      "Yes, within Lagos State.",
    ],
  },
  {
    name: "location language",
    messages: [
      "Where are you guys?",
      "What's your address?",
      "Where is the shop?",
      "How do I find you?",
      "I'm new here, where are you located?",
    ],
    expected: [
      "The Motorcycle Drive, Papa Olonrisa, Ibafo, Ogun State",
      "The Motorcycle Drive, Papa Olonrisa, Ibafo, Ogun State",
      "The Motorcycle Drive, Papa Olonrisa, Ibafo, Ogun State",
      "The Motorcycle Drive, Papa Olonrisa, Ibafo, Ogun State",
      "The Motorcycle Drive, Papa Olonrisa, Ibafo, Ogun State",
    ],
  },
  {
    name: "menu language",
    messages: [
      "Show me your menu.",
      "What food do you sell?",
      "What do you have?",
      "What meals are available?",
    ],
    expected: [
      "available menu information",
      "available menu information",
      "available menu information",
      "available menu information",
    ],
  },
  {
    name: "price language",
    messages: [
      "How much is jollof?",
      "How much is the cheapest?",
      "What's your most expensive meal?",
      "How much is amala?",
      "How much money do I need for jollof?",
    ],
    expected: [
      "Jollof Rice Combo Basic at ₦7,000",
      "Amala & Gbegiri — ₦3,000.",
      "Jollof Rice Combo Full Dish — ₦15,000.",
      "Amala & Gbegiri is ₦3,000.",
      "Jollof Rice Combo Full Dish at ₦15,000",
    ],
  },
  {
    name: "order language",
    messages: [
      "I want to order.",
      "How can I order?",
      "Can I order on WhatsApp?",
      "I want to buy amala.",
      "I want jollof.",
    ],
    expected: [
      "website or WhatsApp",
      "website or WhatsApp",
      "website or WhatsApp",
      "website or WhatsApp",
      "website or WhatsApp",
    ],
  },
  {
    name: "drink language stays bounded",
    messages: [
      "What drinks do you have?",
      "What can I drink with my food?",
      "Give me a drink recommendation.",
      "What's your cheapest drink?",
    ],
    expected: [
      "Drinks are available",
      "Drinks are available",
      "Drinks are available",
      "Current drink options and prices aren't currently available.",
    ],
  },
  {
    name: "restaurant facts and bounded unknowns",
    messages: [
      "What time do you open?",
      "Do you deliver outside Lagos?",
      "What are the ingredients?",
      "What is your delivery fee?",
      "Do you have vegan meals?",
      "What delivery time should I expect?",
    ],
    expected: [
      "9:00 AM–9:00 PM",
      "outside Lagos State isn't available",
      "isn't currently available",
      "Delivery fees depend on location",
      "No dedicated vegan menu",
      "Delivery generally takes around 30 minutes",
    ],
  },
  {
    name: "complete knowledge coverage",
    messages: [
      "Are you open on public holidays?",
      "Do you have a drive-through?",
      "Is there parking available?",
      "What type of food do you serve?",
      "Do you have vegetarian options?",
      "Do you serve vegan food?",
      "Do you have a kids' menu?",
      "What are your most popular dishes?",
      "Do you have gluten-free options?",
      "Can I see your full menu online?",
      "Do you change your menu seasonally?",
      "How much does a meal cost?",
      "Do you sell drinks and desserts?",
      "Can I make a reservation?",
      "How far in advance should I book?",
      "Can I book for a large group?",
      "Is there a minimum spend for reservations?",
      "Can I cancel or reschedule my reservation?",
      "Do you offer takeaway?",
      "How long does delivery take?",
      "Is there a delivery fee?",
      "What's the minimum order for delivery?",
      "Can I track my delivery?",
      "Can I host a private event or birthday party?",
      "Do you offer a birthday package?",
      "Can you cater for outside events?",
      "Do you have a dedicated event planner?",
      "What payment methods do you accept?",
      "Can I pay online when ordering?",
      "Do you offer split bills?",
      "Do you charge a service fee?",
      "Do you cater for people with food allergies?",
      "Are your meat options halal?",
      "Can I request a custom meal if I have dietary restrictions?",
      "Is your restaurant family-friendly?",
      "Is there seating outside?",
      "Do you have Wi-Fi?",
      "Is there background music or live entertainment?",
      "Is your restaurant air-conditioned?",
      "I received the wrong order. What should I do?",
      "My food was cold on delivery. What can I do?",
      "Can I modify my order after placing it?",
      "Do you offer refunds?",
      "Do you have a loyalty or rewards program?",
      "Do you run discounts or promotions?",
      "Do you offer student or corporate discounts?",
      "How do I stay updated on your latest news and offers?",
      "What is your WhatsApp number?",
      "What is your website?",
    ],
    expected: [
      "public holidays",
      "Yes.",
      "parking is available",
      "Nigerian dishes",
      "Yes.",
      "No dedicated vegan menu",
      "No dedicated kids' menu",
      "recommended dishes",
      "Yes. Tell us about dietary restrictions",
      "DamienStore.food.com",
      "updated periodically",
      "Basic dishes start",
      "Dessert information isn't currently available",
      "Reservations are available",
      "as early as possible",
      "Large group bookings",
      "minimum spend",
      "cancel or reschedule",
      "Takeaway orders",
      "around 30 minutes",
      "Delivery fees depend",
      "minimum delivery order",
      "tracked through the website",
      "Private events",
      "Birthday arrangements",
      "Outside-event catering",
      "No dedicated event planner",
      "Cash, bank transfer, and POS",
      "Online payment",
      "Split payments",
      "service charges",
      "allergies before ordering",
      "halal status",
      "Custom meals",
      "welcomes families",
      "Outdoor seating",
      "Wi-Fi",
      "Background music",
      "air-conditioned",
      "WhatsApp",
      "review the complaint",
      "Changes may not be possible",
      "Refunds depend",
      "No dedicated loyalty program",
      "Promotions may be offered",
      "discounts are not guaranteed",
      "latest news and offers",
      "080 32 20 16 72",
      "DamienStore.food.com",
    ],
  },
];

for (const conversation of conversations) {
  for (const [index, message] of conversation.messages.entries()) {
    const reply = getChatbotReply(message);
    const expected = conversation.expected[index];
    assert.ok(
      reply.includes(expected),
      `${conversation.name} failed for "${message}". Got: ${reply}`,
    );
  }
  console.log(`PASS ${conversation.name}`);
}